apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-ai-config
data:
  POSTGRES_DB: finance
  POSTGRES_USER: postgres
  POSTGRES_PORT: "5432"
  API_PORT: "8000"
  FINANCE_API_BASE_URL: http://finance-ai-api:8000
  UV_OFFLINE: "true"
